"""Crowd report data model.

Represents a single crowd report submitted by an event attendee.
Uses domain enums for type safety on all categorical fields.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from app.constants import INPUT_PREVIEW_MAX_LENGTH
from app.models.enums import CrowdDensity, ReportType, Severity


@dataclass
class CrowdReport:
    """Represents a single crowd report from an attendee.

    Attributes:
        input_text: Raw text submitted by the user.
        detected_language: ISO 639-1 language code of the input.
        report_type: AI-classified category of the report.
        severity: Impact severity assigned by the AI.
        title: Short summary generated by the AI.
        location_in_venue: Identified venue location (gate, section, etc.).
        crowd_density: Estimated crowd density at the location.
        timestamp: ISO-8601 UTC timestamp of report creation.
    """

    input_text: str
    detected_language: str = "en"
    report_type: str = ReportType.GENERAL
    severity: str = Severity.INFO
    title: str = ""
    location_in_venue: str = ""
    crowd_density: str = CrowdDensity.UNKNOWN
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_firestore_dict(self) -> dict[str, Any]:
        """Convert to a dict suitable for Firestore storage.

        The ``input_text`` is truncated to ``INPUT_PREVIEW_MAX_LENGTH``
        characters to keep Firestore documents lightweight.
        """
        return {
            "input_preview": self.input_text[:INPUT_PREVIEW_MAX_LENGTH],
            "detected_language": self.detected_language,
            "report_type": self.report_type,
            "severity": self.severity,
            "title": self.title,
            "location_in_venue": self.location_in_venue,
            "crowd_density": self.crowd_density,
            "timestamp": self.timestamp,
        }
